services:
  paymybuddy_app:
    build: .
    container_name: paymybuddy_app
    depends_on:
      paymybuddy_mysql:
        condition: service_healthy
    environment:
      # Utiliser les mêmes credentials que dans le container MySQL
      SPRING_DATASOURCE_URL: jdbc:mysql://paymybuddy_mysql:3306/openclassrooms_paymybuddy?serverTimezone=Europe/Paris
      SPRING_DATASOURCE_USERNAME: openclassrooms
      SPRING_DATASOURCE_PASSWORD: openclassrooms
      # Optionnel : forcer l'attente de la DB
      SPRING_DATASOURCE_INITIALIZATION_MODE: always
    ports:
      - "8083:8080"
    networks:
      - ci-network
    restart: unless-stopped

  paymybuddy_mysql:
    image: mysql:8.0
    container_name: paymybuddy_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mhd02042017
      MYSQL_DATABASE: openclassrooms_paymybuddy
      MYSQL_USER: openclassrooms
      MYSQL_PASSWORD: openclassrooms
    ports:
      - "3308:3306"
    volumes:
      - paymybuddy_mysql_data:/var/lib/mysql
    networks:
      - ci-network
    # Ajout d'un healthcheck pour s'assurer que MySQL est prêt
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "openclassrooms", "-popenclassrooms"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  paymybuddy_mysql_data:

networks:
  ci-network:
    name: ci-network
    external: true