spring:
  server:
    address: 0.0.0.0
    port: 8080

  application:
    name: paymybuddy

  datasource:
    url: jdbc:mysql://paymybuddy_mysql:3306/openclassrooms_paymybuddy?serverTimezone=Europe/Paris&useSSL=false&allowPublicKeyRetrieval=true
    username: openclassrooms
    password: openclassrooms
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Ajout de configurations pour éviter les timeouts
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally-quoted_identifiers: true
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  # Configuration pour éviter les problèmes de démarrage
  sql:
    init:
      mode: always
      continue-on-error: true

# Configuration personnalisée
supported:
  currencies: EUR,USD,XOF,JPY,CNY,RUB,GBP

# Logging pour debug
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE